#### Tensor

Tensor is a specialized multi dimentional array designed for multi dimentional computation   
Dimensions:  
1. Scaler  
2. vector(one dimentional tensor)  
3. two dimentional tensor  
   e.g. 2-D Images  
4. three dimensional tensor  
   e.g. 3-D Images i.e. colored image  
5. n dimentional tensor

In [4]:
import torch

In [8]:
 #creating a tensor

#scalar tensor
x = torch.tensor(1)
print(x)

#vector tensor
x = torch.tensor([1, 2, 3])
print(x)

#matrix tensor
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x)

#3D tensor
x = torch.tensor([[[1, 2], [3, 4]],
                 [[5, 6], [7, 8]]])
print(x)

tensor(1)
tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [11]:
#zeroes
x = torch.zeros(2, 3)
print(x)
print(x.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 3])


In [12]:
#random tensor
x = torch.rand(2, 3)
print(x)

tensor([[0.5641, 0.0623, 0.6716],
        [0.0046, 0.7974, 0.8650]])


In [14]:
#arange
print(torch.arange(0, 10, 2))  # start, end, step
#linspace
print(torch.linspace(0, 10, steps=5))  # start, end, steps
#eye
print(torch.eye(3))  # creates a 3x3 identity matrix
#ones
print(torch.ones(2, 3))  # creates a 2x3 tensor filled with ones
#full
print(torch.full((2, 3), 7))  # creates a 2x3 tensor filled with the value 7

tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[7, 7, 7],
        [7, 7, 7]])


In [16]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
y = torch.empty_like(x)
print(y)
z = torch.zeros_like(x)
print(z)

tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[0, 0, 0],
        [0, 0, 0]])


In [18]:
#tesnor operations

#addition
x = torch.tensor([[1, 2], [3, 4]])
print(x)

print(x + 2)  # adding a scalar
print(x + x)  # adding a tensor

#subtraction
print(x - 2)  # subtracting a scalar
print(x - x)  # subtracting a tensor

#multiplication
print(x * 2)  # multiplying by a scalar
print(x * x)  # element-wise multiplication


tensor([[1, 2],
        [3, 4]])
tensor([[3, 4],
        [5, 6]])
tensor([[2, 4],
        [6, 8]])
tensor([[-1,  0],
        [ 1,  2]])
tensor([[0, 0],
        [0, 0]])
tensor([[2, 4],
        [6, 8]])
tensor([[ 1,  4],
        [ 9, 16]])


In [20]:
#Reduction operations

x= torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x)

#sum
print(torch.sum(x))  # sum of all elements
print(torch.sum(x, dim=0))  # sum along rows
print(torch.sum(x, dim=1))  # sum along columns

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor(21)
tensor([5, 7, 9])
tensor([ 6, 15])


In [22]:
#min
print(torch.min(x))  # minimum value
print(torch.max(x))  # maximum value

tensor(1)
tensor(6)


In [29]:
#matrix operations
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])
print(x)
print(y)

#matrix multiplication
print(torch.matmul(x, y))  # matrix multiplication
print(x @ y)  # using the @ operator for matrix multiplication

#dot product
print(torch.dot(x[0], y[0]))  # dot product of the first row of x and y

#transpose
print(x.T)  # transpose of a matrix


tensor([[1, 2],
        [3, 4]])
tensor([[5, 6],
        [7, 8]])
tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])
tensor(17)
tensor([[1, 3],
        [2, 4]])


In [32]:
x = torch.randint(size = (2, 3), low=1, high=10, dtype=torch.float32)
print(x)

#log
print(torch.log(x))  # natural logarithm

#exponential
print(torch.exp(x))  # exponential function

#sigmoid
print(torch.sigmoid(x))  # sigmoid function

#softmax
print(torch.softmax(x, dim=0))  # softmax along the specified dimension

tensor([[2., 1., 5.],
        [8., 7., 5.]])
tensor([[0.6931, 0.0000, 1.6094],
        [2.0794, 1.9459, 1.6094]])
tensor([[7.3891e+00, 2.7183e+00, 1.4841e+02],
        [2.9810e+03, 1.0966e+03, 1.4841e+02]])
tensor([[0.8808, 0.7311, 0.9933],
        [0.9997, 0.9991, 0.9933]])
tensor([[0.0025, 0.0025, 0.5000],
        [0.9975, 0.9975, 0.5000]])


In [44]:
#tensor operations on cpu vs gpu
if torch.backends.mps.is_available():
    device = torch.device("mps")
    print("MPS device available!")
else:
    device = torch.device("cpu")
    print("MPS not available, using CPU.")
    
n = 15000

x = torch.randn(n, n, device=device)
y = torch.randn(n, n, device=device)

a = torch.randn(n, n)
b = torch.randn(n, n)

import time
start_time = time.time()
torch.mps.synchronize()
result = x @ y
end_time = time.time()
print(f"Time taken for matrix multiplication on {device}: {end_time - start_time:.6f} seconds")

start_time = time.time()
result = a @ b
end_time = time.time()
print(f"Time taken for matrix multiplication on cpu: {end_time - start_time:.6f} seconds")



MPS device available!
Time taken for matrix multiplication on mps: 0.062923 seconds
Time taken for matrix multiplication on cpu: 6.200946 seconds
